name: cat_breeds_pragma
description: "Cat Breeds App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.7.0
  modal_progress_hud_nsn: ^0.5.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
